[project]
name = "nano-llama-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "safetensors>=0.7.0",
    "torch>=2.9.1",
    "torchview>=0.2.7",
]
